### ISSUE TITLE
ASAP not responding when loading large XML annotations.

### ISSUE THREAD

**Issue by aled88** [GeertLitjens/ASAP#55]
I tried to load a point annotation xml file which is around ~50MB but ASAP 1.7 and 1.6 become not responding or just freeze for more than an hour.

my laptop spec is i7-6700hq,12gb ram,512gb ssd , 950m 4gb gpu ,windows 10 64bit

i have the coordinate.xml file if you want to check it out for me.

https://drive.google.com/file/d/0B15axUcMKU8eSXlMSlhOdEp0U2s/view?usp=sharing

**Comment by GeertLitjens** [comment]
Hi, the problem is that you are essentially trying to draw more than 200000 points, which is essentially a point cloud. ASAP will draw a rectangle for each and everyone of those points which will make it slow to a crawl/standstill. A way around this is to add some specific tools for drawing points clouds such that overlapping points at low resolution are not drawn, but this is not part of ASAP and not very high on the priority list.
